language: php

php:
  - "5.6"

services:
  - mongodb

cache:
    directories:
      - "$HOME/.composer/cache"
      - "$HOME/.npm"

env:
  - PECLMONGO=mongo-1.6.10

before_install:
  - sudo apt-get update > /dev/null
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"

install:
  # install php packages required for running YAWIK phpunit tests
  - sudo apt-get install -y --force-yes php5-intl php5-curl php5-xsl
  # install npm to manage js assets
  - sudo apt-get install -y nodejs

  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  # copy default app config
  - mkdir -p config/autoload
  - mkdir -p build/behat
  - cp .travis/autoload/*.* config/autoload

  # install Mongo extension
  - sh -c "wget http://pecl.php.net/get/$PECLMONGO.tgz"
  - sh -c "tar xfz $PECLMONGO.tgz"
  - sh -c "cd $PECLMONGO && phpize && ./configure && make && sudo make install"

  - phpenv config-add .travis/phpenv.ini
  - ./install.sh -b .travis/build.properties.travis
  - ./composer.phar self-update
  - ./composer.phar install --dev

  # setup display, behat, and selenium
  - ./bin/start-selenium.sh > /dev/null 2>&1 &
  - sleep 5
  - APPLICATION_ENV=development php -S localhost:8000 -t public public/index.php > /dev/null 2>&1 &
  - sleep 3


script:
  - ./vendor/bin/phpunit -c test
  - APPLICATION_ENV=development ./vendor/bin/behat --strict --no-interaction --tags="~@skip-travis"

after_script:
  - cd $TRAVIS_BUILD_DIR
  - "./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles \"build/behat/*.log\""
  - "./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles \"log/*.log\""
  - "./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles \"log/tracy/*.*\""
  - "IMGUR_CLIENT_ID=bec050c54e1bb52 ./bin/imgur-uploader.sh build/behat/*.png"
  - ls -l test/build/logs
  - php vendor/bin/coveralls -vvv
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.serialized

